### ISSUE TITLE
Android Build failed.

### ISSUE THREAD

**Issue by SeanRenet** [codersera-repo/expo-native-starter-kit#1]
Build file '/Users/myname/Sites/mydirectory/Downloads/expo-native-starter-kit-test/node_modules/expo-gl-cpp/android/build.gradle' line: 55

* What went wrong:
A problem occurred evaluating project ':expo-gl-cpp'.
> Cannot get property 'absolutePath' on null object

I am currently running

```
MacOS Mojave 10.14.5
Android Studio 3.4.2
VS Code 1.36.1
react-native-cli: 2.0.1
react-native: 0.60.4
Gradle 4.10.2!
expo-cli 3.0.9
```

ios works perfect.

**Comment by arshadmhd** [comment]
You need to run your application from the android studio instead of the cli.
There are ways in which you can do so from the cli as well but that requires a bit of modification in the expo script. It is an issue from expo.

**Comment by codersera-repo** [comment]
You need to run the app from android studio instead of the cli.
Expo script has this issue. 

The same is mentioned in our README as well. 
Please re-open this issue, if the above doesn't fix the problem.

**Comment by SeanRenet** [comment]
@codersera-repo Isn't the whole point of expo is to run stuff through its CLI until its built or ejected?  I am not even sure how to build the android folder while using a managed expo app

**Comment by codersera-repo** [comment]
@SeanRenet What you need to do is to just open the settings.gradle file, placed in your android folder of the project, in android studio. And click on the run button in android studio, that should be good enough.

Yes, expo helps you by providing the cli, and this starter kit is more for the advanced use case, where you want to have expo and run custom native modules at the same time.

The recommendation is to not use this starter kit unless you exactly know why is this helpful.

To help run this from the command line, follow this issue on expo. https://github.com/expo/expo/issues/4483
