### ISSUE TITLE
npm run web errors with expo-modal

### ISSUE THREAD

**Issue by jmatsushita** [codersera-repo/expo-native-starter-kit#5]
I get errors when running `npm run web` the console shows:
```
.../App.js
Attempted import error: 'Modal' is not exported from 'expo-modal'.

.../App.js
Attempted import error: 'dismissModal' is not exported from 'expo-modal'.

.../App.js
Attempted import error: 'showModal' is not exported from 'expo-modal'.
```

And the browser page shows further errors:
```
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
Module.<anonymous>
node_modules/expo-modal/index.js:19
  16 |     }
  17 | }
  18 | 
> 19 | module.exports = {
  20 |     Modal,
  21 |     showModal: Util.showModal,
  22 |     dismissModal: Util.dismissModal,
```

**Comment by jmatsushita** [comment]
Removing the `expo-modal` related imports in `App.js` fixes the issue. It would be great if you aimed to maintain `react-native-web` compatibility, so maybe having an `App.web.js` without `expo-modal` would be one way to address this? Another, since it seems you're maintaining the `expo-modal` package, would be to offer `react-native-web` compatibility for it, so I created an issue there https://github.com/codersera-repo/expo-modal/issues/1

Thanks for the very cool project!

**Comment by codersera-repo** [comment]
thanks @jmatsushita 

the above issue suggested by you is fixed now.
